### ISSUE TITLE
sintesis 

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/actividad-3-sintesis-ArturoAngonJose#2]
[Sintesis_Arturo Angon Jose.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-ArturoAngonJose/files/9463542/Sintesis_Arturo.Angon.Jose.pdf)

**Comment by javiern-778** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
